# 导出一些环境变量 （some environment variables to be used）
# OHNO_CERT_DIR: 保存证书的目录，如（Windows D:\DockerCompose\etcd\pki；MacOS 或 Linux /Users/username/etcd/pki）
# OHNO_ETCD1_DATA_DIR: 第一个 ETCD 节点（ETCD1）的数据目录，如（Windows D:\DockerCompose\etcd\etcd1-data；MacOS 或 Linux /Users/username/etcd/data1）
# OHNO_ETCD2_DATA_DIR: 第二个 ETCD 节点（ETCD2）的数据目录，如（Windows D:\DockerCompose\etcd\etcd2-data；MacOS 或 Linux /Users/username/etcd/data2）
# OHNO_ETCD3_DATA_DIR: 第三个 ETCD 节点（ETCD3）的数据目录，如（Windows D:\DockerCompose\etcd\etcd3-data；MacOS 或 Linux /Users/username/etcd/data3）
# OHNO_REPO: 代码仓库目录，如（Windows D:\Repositories\ohno；MacOS 或 Linux /Users/username/Repositories/ohno）
# OHNO_ARCH: CPU 架构，仅支持 aarch64 或 x86_64 两种

networks:
  cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  # 生成证书
  cert:
    image: ohno-cert:latest
    build:
      dockerfile: Dockerfile-cert
    container_name: cert
    networks:
      - cluster-net
    volumes:
      - $OHNO_CERT_DIR:/etc/etcd/pki
    command: /bin/bash -c "cp -f /cert/* /etc/etcd/pki"

  # ETCD 集群节点 1 (初始启动节点)
  etcd1:
    image: quay.io/coreos/etcd:v3.6.0
    container_name: etcd1
    networks:
      cluster-net:
        ipv4_address: 172.22.0.11
    environment:
      - ETCD_NAME=etcd1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://etcd1:2379
      - ETCD_INITIAL_CLUSTER=etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_CLIENT_CERT_AUTH=true
      - ETCD_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_KEY_FILE=/etc/etcd/pki/etcd-key.pem
      - ETCD_PEER_CLIENT_CERT_AUTH=true
      - ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_PEER_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_PEER_KEY_FILE=/etc/etcd/pki/etcd-key.pem
    volumes:
      - $OHNO_ETCD1_DATA_DIR:/etcd-data
      - $OHNO_CERT_DIR:/etc/etcd/pki
    depends_on:
      - cert
    healthcheck:
      test: ["CMD", "etcdctl", "--cacert=/etc/etcd/pki/ca.pem", "--cert=/etc/etcd/pki/etcd.pem", "--key=/etc/etcd/pki/etcd-key.pem", "endpoint", "health"]
      interval: 15s
      timeout: 10s
      retries: 3

  # ETCD 集群节点 2
  etcd2:
    image: quay.io/coreos/etcd:v3.6.0
    container_name: etcd2
    networks:
      cluster-net:
        ipv4_address: 172.22.0.12
    environment:
      - ETCD_NAME=etcd2
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://etcd2:2379
      - ETCD_INITIAL_CLUSTER=etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_CLIENT_CERT_AUTH=true
      - ETCD_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_KEY_FILE=/etc/etcd/pki/etcd-key.pem
      - ETCD_PEER_CLIENT_CERT_AUTH=true
      - ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_PEER_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_PEER_KEY_FILE=/etc/etcd/pki/etcd-key.pem
    volumes:
      - $OHNO_ETCD2_DATA_DIR:/etcd-data
      - $OHNO_CERT_DIR:/etc/etcd/pki
    depends_on:
      etcd1:
        condition: service_started

  # ETCD 集群节点 3
  etcd3:
    image: quay.io/coreos/etcd:v3.6.0
    container_name: etcd3
    networks:
      cluster-net:
        ipv4_address: 172.22.0.13
    environment:
      - ETCD_NAME=etcd3
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=https://etcd3:2379
      - ETCD_INITIAL_CLUSTER=etcd1=https://etcd1:2380,etcd2=https://etcd2:2380,etcd3=https://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_CLIENT_CERT_AUTH=true
      - ETCD_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_KEY_FILE=/etc/etcd/pki/etcd-key.pem
      - ETCD_PEER_CLIENT_CERT_AUTH=true
      - ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/pki/ca.pem
      - ETCD_PEER_CERT_FILE=/etc/etcd/pki/etcd.pem
      - ETCD_PEER_KEY_FILE=/etc/etcd/pki/etcd-key.pem
    volumes:
      - $OHNO_ETCD3_DATA_DIR:/etcd-data
      - $OHNO_CERT_DIR:/etc/etcd/pki
    depends_on:
      etcd1:
        condition: service_started

  # 开发环境容器
  dev-env:
    image: ohno-dev:latest
    build:
      dockerfile: Dockerfile-dev
      args:
        - ARCH=$OHNO_ARCH
    container_name: dev-env
    networks:
      - cluster-net
    volumes:
      - $OHNO_REPO:/ohno
      - $OHNO_CERT_DIR:/etc/etcd/pki
    environment:
      - ETCDCTL_API=3
      - ETCD_ENDPOINTS=https://etcd1:2379,https://etcd2:2379,https://etcd3:2379
    command: sleep infinity
    depends_on:
      - cert
      - etcd1
      - etcd2
      - etcd3
